version: '3.7'

services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    restart: always    
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888     
       
  kafka:
    image: ubuntu/kafka
    hostname: kafka
    container_name: kafka    
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"      
    depends_on:
      - zookeeper      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
               
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8090:8080"
    depends_on:
      - kafka
      - zookeeper
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:29092,localhost:29092,localhost:9092,kafka:9092'

      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      #AUTH_TYPE: "LOGIN_FORM"
      #SPRING_SECURITY_USER_NAME: admin
      #SPRING_SECURITY_USER_PASSWORD: pass